### PR TITLE
Replace forward slash encoding with underscores & update build to latest LTS Jenkins release.

### PR DESCRIPTION
**Pull request by CliffFoster**
Updated plugin to use latest LTS version of Jenkins extending SlaveToMasterFileCallable instead of implementing FilePath.FileCallable.

Replace forward slash encoding with underscore to maintain compatability with multibranch plugins that allow foward slashes in names and maintain Windows node workspace compatibility.

Updated tests to include forward slash replacement handling.

### CODE REVIEW

**Comment by CliffFoster** [comment]
If preferable, can just include slash replacing and not update the pom. That was only done to test against newer plugins than the normal Jenkins release specified in the pom.

**Comment by amarruedo** [comment]
I'm facing forward slash encoding issue, would be nice to add this improvement

**Comment by CliffFoster** [comment]
It has been immensely helpful. We run a Xilinx FPGA toolchain at the shop I work at and the resulting generated paths are extremely long sometimes and hit Windows limits, so this plugin has been critical. Making it more Windows friendly was a must because of the nature of the Xilinx tools.

**Comment by olivergondza** [comment]
Forward slash issue addressed in https://github.com/jenkinsci/short-workspace-path-plugin/pull/4

**Pull request closed without merging**
